### PR TITLE
Changes to the original code by using EMD instead of VMD.

### PR DESCRIPTION
**Pull request by Anirudh2465**
EMD was used to replace VMD due to its computational efficiency when compared to VMD. Other than EMD, DMD and Wavelet transformation was also tried out, from which both caused trouble due to dimensionality problems.

### CODE REVIEW

**Review by SaranDharshanSP — CHANGES_REQUESTED** [review]
Looks Good to me.
Do update the results in the Readme then it could be merged

**Comment by Anirudh2465** [comment]
I have updated the results in the ReadME

**Review by SaranDharshanSP — APPROVED** [review]
LGTM

**Pull request merged**
